services:
  photoreview:
    build: .
    container_name: photoreview
    env_file:
      - .env
    ports:
      - "127.0.0.1:18000:5000"
    environment:
      PHOTO_REVIEW_DB_PATH: "/data/photoreview.db"
      PHOTO_REVIEW_UPLOADS_DIR: "/data/uploads"
    volumes:
      - /var/www/html/gibdd90.multfilm.tatar/data:/data
    restart: always
